"""Change availability to boolean

Revision ID: 3617b2bbca98
Revises: 701a2fd97716
Create Date: 2025-03-08 07:11:57.933823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3617b2bbca98'
down_revision = '701a2fd97716'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.alter_column('availability',
               existing_type=sa.VARCHAR(),
               type_=sa.Boolean(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.alter_column('availability',
               existing_type=sa.Boolean(),
               type_=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
